### ISSUE TITLE
Use of the library outside Laravel

### ISSUE THREAD

**Issue by socrates77** [mattiabasone/PagOnline#1]
Hi,
I want to integrate the library in WordPress. 
Do you think it's possible?

**Comment by mattiabasone** [comment]
Once you have installed it using composer you should be able to use it as shown in the "[demo](https://github.com/mattiabasone/PagOnline/tree/master/tests/demo)" scripts. 

If you don't have composer installed on the remote server, you can can run `composer require mattiabasone/pagonline` locally then move `vendor/` directory to the remote host.

**Comment by socrates77** [comment]
Thanks a lot.
It will save me hours of cold sweat!
