### ISSUE TITLE
Retro Compatibilità PHP

### ISSUE THREAD

**Issue by shinesoftware** [mattiabasone/PagOnline#3]
Salve,

prima di tutto ti ringrazio per aver realizzato questa classe che è veramente molto utile. Volevo chiederti se c'è modo di poterla usare in un ambiente con PHP 7.1. C'è la possibilità di usarla con la versione 7.1 in qualche modo? Quali sono le sezioni esposte alla versione PHP 7.2? 

Grazie mille

**Comment by mattiabasone** [comment]
Ciao, l'aggiornamento fatto nella versione 2.0.0 è legato principalmente all'upgrade di Laravel e contiene alcune ottimizzazioni.
Hai già provato ad installare la versione 1.0.1?

**Comment by shinesoftware** [comment]
Ciao,

no sinceramente non l'ho ancora fatto! E' identica alla versione 2.0.0 ma compatibile con la versione PHP 7.1?

grazie

**Comment by mattiabasone** [comment]
> Ciao,
> 
> no sinceramente non l'ho ancora fatto! E' identica alla versione 2.0.0 ma compatibile con la versione PHP 7.1?
> 
> grazie

Si, dovrebbe avere le stesse funzionalità.
Fammi sapere se riscontri problemi
